global:
  scrape_interval: 15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093
rule_files:
scrape_configs:
  - job_name: "docker"
    static_configs:
      - targets: [ "localhost:9090" ]
  - job_name: "fundingboost"
    metrics_path: '/api/v1/fundingboost/prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: [ 'backend:8080' ]